### PR TITLE
common: fixed build issues

### PR DESCRIPTION
**Pull request by mohan43u**
not able to compile with latest zig 0.11.0-dev.1638+7199d7c77

### CODE REVIEW

**Comment by ifreund** [comment]
Hello, thanks for the patch but zig-wayland has the policy of supporting only the latest zig release, not master branch.

I will personally update to the zig master branch shortly before 0.11.0 is released to make sure there are no regressions affecting zig-wayland but I do not have any plans to maintain a branch compatible with zig master throughout the entire zig release cycle.

**Comment by mohan43u** [comment]
understood. I fixed the build issues while compiling rivercarro project, zig-wayland is a dependency to that project. I fixed those build issues, thought of providing that fixed changes.

**Comment by ifreund** [comment]
I believe rivercarro also depends on Zig 0.10 and is not compatible with zig master.

**Comment by mohan43u** [comment]
yes, rivercarro also tracks zig stable releases and the author also told he will fix any build issues once zig 0.11 comes out.

**Pull request closed without merging**
