### PR TITLE
updated to zig master

### PR DESCRIPTION
**Pull request by Sobeston**
Here's my shot at updating to master, `zig build test` works.

### CODE REVIEW

**Comment by Sobeston** [comment]
Wow, I just realised someone already did it with https://github.com/ifreund/zig-wayland/pull/49. Feel free to close.

**Comment by ifreund** [comment]
It would be nice to diff the 2 PRs and see how they differ xD

**Comment by Cloudef** [comment]
lol.. i was about to do 3rd PR ...

**Comment by ifreund** [comment]
Thanks for the PR, I went with #49 as the author took the time to get rid of the unnecessary `@as()` usage.

**Pull request closed without merging**
